const NEXT_PUBLIC_GOOGLE_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_API_KEY
const NEXT_PUBLIC_GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID
const NEXT_PUBLIC_GOOGLE_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET
const NEXT_PUBLIC_SECRET = process.env.NEXT_PUBLIC_SECRET
const NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
const NEXT_PUBLIC_CLOUDINARY_API_KEY =
  process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY
const NEXT_PUBLIC_CLOUDINARY_API_SECRET =
  process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET
const NEXT_PUBLIC_CLOUDINARY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_URL
const NEXT_PUBLIC_CLOUDINARY_BASE_URL =
  process.env.NEXT_PUBLIC_CLOUDINARY_BASE_URL
const NEXT_PUBLIC_DATABASE_URL = process.env.NEXT_PUBLIC_DATABASE_URL
const NEXT_PUBLIC_DIRECT_URL = process.env.NEXT_PUBLIC_DIRECT_URL
const NEXT_PUBLIC_PROXY_URL = process.env.NEXT_PUBLIC_PROXY_URL

export const env = {
  NEXT_PUBLIC_GOOGLE_API_KEY,
  NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
  NEXT_PUBLIC_SECRET,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_API_KEY,
  NEXT_PUBLIC_CLOUDINARY_API_SECRET,
  NEXT_PUBLIC_CLOUDINARY_URL,
  NEXT_PUBLIC_CLOUDINARY_BASE_URL,
  NEXT_PUBLIC_DATABASE_URL,
  NEXT_PUBLIC_DIRECT_URL,
  NEXT_PUBLIC_PROXY_URL,
}
